language: node_js
env:
  - TARGET=test
node_js:
  - "10"
  - "12"
  - "14"
before_install: "sudo apt-get update && sudo apt-get install -y graphicsmagick libjpeg-turbo-progs"
script: npm run $TARGET
matrix:
  include:
    - name: Lint
      node_js: '10'
      env:
        - TARGET=lint
    - name: Coverage
      node_js: '10'
      env:
        - TARGET=coverage
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
