language: node_js
node_js:
  - "10"
  - "12"
  - "14"
before_install: "sudo apt-get update && sudo apt-get install -y graphicsmagick libjpeg-turbo-progs"
script:
  - "npm test"
  - "npm run coverage"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
